version: '3'
services:
  db_signal:
    image:          lgaete/postgres_multiple-databases
    container_name: db_signal
    restart:        always
    environment:
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES: signal_db,accounts_db,db_message,db_abuse
    ports:
      - '5432:5432'
  redis_master:
    image: redis:5
    container_name: redis_master
    restart:        always
    ports:
      - '6379:6379'
    volumes:
      - ./redis/redis_master:/data
  redis_slave:
    image: redis:5
    container_name: redis_slave
    restart:        always
    command: redis-server --port 6380 --slaveof redis_master 6379
    ports:
      - '6380:6380'
    volumes:
      - ./redis/redis_slave:/data
  sentinel:
    build: ./sentinel
    container_name: redis_sentinel
    restart:        always
    ports:
      - '26379:26379'
    environment:
      - SENTINEL_NAME=mysentinel
      - HOST_IP=127.0.0.1
    volumes:
      - ./redis/redis_slave:/data
